In [19]:
# Membuat list
data = [10, 20, 'Python', True, 1]
# Akses & slicing
print(data[0]) # → 10
print(data[-1]) # → 3.14 (dari belakang)
print(data[1:3]) # → [20, 'Python']
# Manipulasi
data.append(99) # tambah di akhir
data.insert(1, 55) # sisipkan di posisi 1
data.remove(20) # hapus nilai pertama = 20
data.sort(key=str) # urutkan (jika tipe sama)
print(data)






10
1
[20, 'Python']
[1, 10, 55, 99, 'Python', True]


In [20]:
mahasiswa = {
 'nama': 'Budi Santoso',
 'nim': '2024001',
 'prodi': 'Informatika',
 'ipk': 3.85
}
# Akses nilai
print(mahasiswa['nama']) # → 'Budi Santoso'
print(mahasiswa.get('usia', 0)) # default jika key tak ada
# Update dan hapus
mahasiswa['angkatan'] = 2024 # tambah key baru
del mahasiswa['nim'] # hapus key


Budi Santoso
0


In [26]:
import numpy as np
# Dari list Python
a1D = np.array([1, 2, 3, 4, 5]) # 1D
a2D = np.array([[1,2,3],[4,5,6]]) # 2D
# Array dengan nilai inisial
zeros = np.zeros((3, 4)) # nol semua
ones = np.ones((2, 3)) # satu semua
eye = np.eye(4) # matriks identitas
full = np.full((2, 2), 7) # nilai konstan
# Sequence
arange = np.arange(0, 20, 2) # 0,2,4,...18
linsp = np.linspace(0, 1, 11) # 11 titik merata
# Array acak (reproducible)
rng = np.random.default_rng(seed=42)
rand_int = rng.integers(0, 100, (3, 4))
rand_flt = rng.normal(loc=0, scale=1, size=(100,))
print(rand_flt)


[ 0.1278404  -0.31624259 -0.01680116 -0.85304393  0.87939797  0.77779194
  0.0660307   1.12724121  0.46750934 -0.85929246  0.36875078 -0.9588826
  0.8784503  -0.04992591 -0.18486236 -0.68092954  1.22254134 -0.15452948
 -0.42832782 -0.35213355  0.53230919  0.36544406  0.41273261  0.430821
  2.1416476  -0.40641502 -0.51224273 -0.81377273  0.61597942  1.12897229
 -0.11394746 -0.84015648 -0.82448122  0.65059279  0.74325417  0.54315427
 -0.66550971  0.23216132  0.11668581  0.2186886   0.87142878  0.22359555
  0.67891356  0.06757907  0.2891194   0.63128823 -1.45715582 -0.31967122
 -0.47037265 -0.63887785 -0.27514225  1.49494131 -0.86583112  0.96827835
 -1.68286977 -0.33488503  0.16275307  0.58622233  0.71122658  0.79334724
 -0.34872507 -0.46235179  0.85797588 -0.19130432 -1.27568632 -1.13328721
 -0.91945229  0.49716074  0.14242574  0.69048535 -0.42725265  0.15853969
  0.62559039 -0.30934654  0.45677524 -0.66192594 -0.36305385 -0.38173789
 -1.19583965  0.48697248 -0.46940234  0.01249412  0.48

In [27]:
# Operasi aritmetika vektorisasi
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])
print(a + b) # → [11 22 33 44 55]
print(a * b) # → [10 40 90 160 250]
print(a ** 2) # → [1 4 9 16 25]
# Universal functions (ufuncs)
np.sqrt(a) # akar kuadrat tiap elemen
np.exp(a) # eksponensial (e^x)
np.log(b) # logaritma natural
# Fungsi statistik
data = rng.normal(0, 1, 1000)
print(f'Mean: {np.mean(data):.4f}')
print(f'Std: {np.std(data):.4f}')
print(f'Min: {np.min(data):.4f}')
print(f'Max: {np.max(data):.4f}')
print(f'Q1: {np.percentile(data,25):.4f}')
print(f'Q3: {np.percentile(data,75):.4f}')

[11 22 33 44 55]
[ 10  40  90 160 250]
[ 1  4  9 16 25]
Mean: -0.0163
Std: 1.0008
Min: -3.6484
Max: 3.1789
Q1: -0.6897
Q3: 0.6163


In [28]:
import pandas as pd
# Series dari list — index default 0,1,2...
s1 = pd.Series([85, 92, 78, 95, 88])
# Series dengan index kustom
nilai = pd.Series(
 [85, 92, 78, 95],
 index=['Alice','Bob','Caca','Dina']
)
print(nilai['Bob']) # → 92
print(nilai[nilai>80]) # filter
print(nilai.mean()) # → 87.5
print(nilai.describe()) # statistik lengkap

92
Alice    85
Bob      92
Dina     95
dtype: int64
87.5
count     4.000000
mean     87.500000
std       7.593857
min      78.000000
25%      83.250000
50%      88.500000
75%      92.750000
max      95.000000
dtype: float64


In [29]:
# Membuat DataFrame dari dictionary
data = {
 'nama': ['Ali','Budi','Caca','Dina'],
 'usia': [22, 25, 21, 23],
 'kota': ['Jakarta','Bandung','Surabaya','Medan'],
 'ipk': [3.8, 3.5, 3.9, 3.7]
}
df = pd.DataFrame(data)
# Informasi dasar
print(df.shape) # → (4, 4)
print(df.dtypes) # tipe data per kolom
print(df.columns) # nama-nama kolom


(4, 4)
nama     object
usia      int64
kota     object
ipk     float64
dtype: object
Index(['nama', 'usia', 'kota', 'ipk'], dtype='object')


In [35]:
# 1. WAJIB import library pandas terlebih dahulu
import pandas as pd

# ==========================================
# CONTOH 1: Memuat dari URL (Dataset Publik)
# ==========================================
# Gunakan link 'Raw' dari GitHub, bukan link halaman repositori
url = "https://raw.githubusercontent.com/plotly/datasets/refs/heads/master/cone_plot_data.csv"
df_url = pd.read_csv(url)

print("--- 5 Baris Pertama Data dari URL ---")
print(df_url.head())
print("\n")

# ==========================================
# CONTOH 2: Memuat dari File Lokal (dengan Parameter)
# ==========================================
# Catatan: Pastikan kamu benar-benar memiliki file bernama 'data.csv'
# di dalam folder yang sama dengan script Python ini.

try:
    df_lokal = pd.read_csv('data.csv',
        sep=';',                 # pemisah kolom (default ',')
        encoding='utf-8',        # encoding file
        index_col='ID',          # kolom sebagai index (Pastikan kolom 'ID' ada di file)
        parse_dates=['tgl'],     # parse kolom tanggal (Pastikan kolom 'tgl' ada di file)
        na_values=['N/A','none'] # menganggap 'N/A' dan 'none' sebagai data kosong (NaN)
    )

    # Eksplorasi standar setelah load
    print("--- 5 Baris Pertama Data Lokal ---")
    print(df_lokal.head())

    print("\n--- Tipe Data & Missing Values ---")
    df_lokal.info()

    print("\n--- Statistik Deskriptif ---")
    print(df_lokal.describe())

except FileNotFoundError:
    print("ERROR: File 'data.csv' tidak ditemukan. Pastikan file ada di foldermu atau lewati bagian ini.")
except ValueError as e:
    print(f"ERROR Parameter: {e}. (Biasanya karena kolom 'ID' atau 'tgl' tidak ada di dalam file data.csv milikmu)")

--- 5 Baris Pertama Data dari URL ---
         u        v         w       x     y      z
0  0.56851  0.62783 -0.001017  70.188  17.5 -0.002
1  0.56851  0.62783 -0.001017  71.791  17.5 -0.002
2  0.56851  0.62783 -0.001017  73.393  17.5 -0.002
3  0.87909  0.62783 -0.001017  74.996  17.5 -0.002
4  0.56851  0.62783 -0.001017  76.599  17.5 -0.002


ERROR: File 'data.csv' tidak ditemukan. Pastikan file ada di foldermu atau lewati bagian ini.


In [40]:
# Contoh: Dataset Titanic
df = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv')
# Filter satu kondisi
penumpang_selamat = df[df['Survived'] == 1]
penumpang_wanita = df[df['Sex'] == 'female']
# Filter kondisi ganda (& = AND, | = OR)
wanita_kelas1 = df[(df['Sex']=='female') &
 (df['Pclass']==1)]
# Seleksi kolom tertentu
df[['Name','Age','Sex','Survived']]

# Pola dasar: groupby → aggregation
df.groupby('Pclass')['Survived'].mean()
# Agregasi multiple kolom & fungsi
hasil = df.groupby('Pclass').agg(
 total = ('PassengerId', 'count'),
 selamat = ('Survived', 'sum'),
 pct_selamat= ('Survived', 'mean'),
 rata_usia = ('Age', 'mean'),
 max_fare = ('Fare', 'max')
)
hasil = hasil.round(3)
print(hasil)
# GroupBy multi-kolom
df.groupby(['Pclass','Sex'])['Survived']\
 .mean().unstack().round(3)



        total  selamat  pct_selamat  rata_usia  max_fare
Pclass                                                  
1         216      136        0.630     38.233   512.329
2         184       87        0.473     29.878    73.500
3         491      119        0.242     25.141    69.550


Sex,female,male
Pclass,,
1,0.968,0.369
2,0.921,0.157
3,0.500,0.135
